### ISSUE TITLE
Object [object Array] has no method 'find'     at Object.service.getUser 

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#196]
when logged in aj JTest1, activity feed is not rendered properly due to:

```
TypeError: Object [object Array] has no method 'find'
    at Object.service.getUser (http://192.168.43.176:8100/js/services/follows.js:125:26)
    at http://192.168.43.176:8100/js/services/follows.js:86:25
    at Array.forEach (native)
    at http://192.168.43.176:8100/js/services/follows.js:84:29
    at http://192.168.43.176:8100/lib/ionic/js/ionic.bundle.min.js:151:182
    at n.$eval (http://192.168.43.176:8100/lib/ionic/js/ionic.bundle.min.js:165:493)
    at n.$digest (http://192.168.43.176:8100/lib/ionic/js/ionic.bundle.min.js:163:9)
    at n.$apply (http://192.168.43.176:8100/lib/ionic/js/ionic.bundle.min.js:166:269)
    at l (http://192.168.43.176:8100/lib/ionic/js/ionic.bundle.min.js:118:152)
    at F (http://192.168.43.176:8100/lib/ionic/js/ionic.bundle.min.js:122:187)
    at XMLHttpRequest.K.onload 
```

**Comment by petervojtek** [comment]
fixed
