### ISSUE TITLE
Arrived push notification fails due to Object #<Object> has no method 'vibrate

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#229]
```
TypeError: Object #<Object> has no method 'vibrate'
    at http://192.168.43.176:8100/js/services/notifications.js:49:32
    at n.$eval (http://192.168.43.176:8100/lib/ionic/js/ionic.bundle.min.js:165:493)
    at n.$apply (http://192.168.43.176:8100/lib/ionic/js/ionic.bundle.min.js:166:217)
    at http://192.168.43.176:8100/js/services/notifications.js:45:23
    at http://192.168.43.176:8100/js/services/notifications.js:27:9
    at PushNotification.emit (http://192.168.43.176:8100/plugins/phonegap-plugin-push/www/push.js:194:38)
    at success (http://192.168.43.176:8100/plugins/phonegap-plugin-push/www/push.js:51:18)
    at Object.cordova.callbackFromNative (http://192.168.43.176:8100/cordova.js:293:58)
    at processMessage (http://192.168.43.176:8100/cordova.js:1081:17)
    at processMessages (http://192.168.43.176:8100/cordova.js:1104:9)
    at pollOnce (http://192.168.43.176:8100/cordova.js:973:9)
    at pollOnceFromOnlineEvent (http://192.168.43.176:8100/cordova.js:960:5) ionic.bundle.min.js:139

```

**Comment by petervojtek** [comment]
fixed
