### ISSUE TITLE
Influences: unable to follow friend from Facebook due to TypeError: Object #<Object> has no method '$changeStatus'

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#294]
there is business logic in legacy code which should automatically load friends from facebook and display then somehow in Influences view. this was never tested and not sure if it is working at all.

**Comment by jterps08** [comment]
It also may be good to show this on the Friend Finder screen so that the user has something to look at while the system is working on the hash comparison of the user's address book.

**Comment by petervojtek** [comment]
the workflow which fetches friends from facebook really works:

<img width="312" alt="screen shot 2016-09-29 at 14 33 40" src="https://cloud.githubusercontent.com/assets/225506/18954167/f60590e0-8651-11e6-900e-d9e2a42488c2.png">

however when trying to follow such a person in powerline app I experience this error:

```
TypeError: Object #<Object> has no method '$changeStatus'
    at n.$scope.facebookFollow (http://192.168.0.103:8100/js/controllers/influences/influences_search_ctrl.js:42:10)
    at fn (eval at <anonymous> (http://192.168.0.103:8100/lib/ionic/js/ionic.bundle.min.js:243:83), <anonymous>:4:300)
    at http://192.168.0.103:8100/lib/ionic/js/ionic.bundle.min.js:446:6438
    at n.$eval (http://192.168.0.103:8100/lib/ionic/js/ionic.bundle.min.js:165:493)
    at n.$apply (http://192.168.0.103:8100/lib/ionic/js/ionic.bundle.min.js:166:217)
    at HTMLParagraphElement.<anonymous> (http://192.168.0.103:8100/lib/ionic/js/ionic.bundle.min.js:446:6420)
    at HTMLParagraphElement.n.event.dispatch (http://192.168.0.103:8100/lib/jquery/dist/jquery.min.js:3:6466)
    at HTMLParagraphElement.r.handle (http://192.168.0.103:8100/lib/jquery/dist/jquery.min.js:3:3241)
    at n (http://192.168.0.103:8100/lib/ionic/js/ionic.bundle.min.js:22:384)
    at t (http://192.168.0.103:8100/lib/ionic/js/ionic.bundle.min.js:22:216)
    at HTMLDocument.l (http://192.168.0.103:8100/lib/ionic/js/ionic.bundle.min.js:22:1451) 
```

**Comment by jterps08** [comment]
In the future, we can make friend suggestions based on:

People who are both in the user's town/state/country groups AND in some other group (e.g. Save the Whales) that they've joined. 
People who share similar interests
People who have created similar groups
