### ISSUE TITLE
Facebook share button not working due to Object #<Object> has no method 'ui'

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#306]
on Android when clicked Facebook share button on announcement, or in Post detail:

```
TypeError: Object #<Object> has no method 'ui'
    at Object.share (file:///android_asset/www/js/services/facebook.js:112:10)
    at n.$scope.FBShare (file:///android_asset/www/js/controllers/widget.js:31:14)
    at fn (eval at <anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:243:83), <anonymous>:4:212)
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:446:6438
    at n.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:165:493)
    at n.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:166:217)
    at HTMLUnknownElement.<anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:446:6420)
    at HTMLUnknownElement.n.event.dispatch (file:///android_asset/www/lib/jquery/dist/jquery.min.js:3:6466)
    at HTMLUnknownElement.r.handle (file:///android_asset/www/lib/jquery/dist/jquery.min.js:3:3241)
    at n (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:22:384)
    at t (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:22:216)
    at HTMLDocument.l (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:22:1451) 
```

**Comment by petervojtek** [comment]
@jterps08, what is the Facebook (and other) share buttons supposed to share?

The point is, it may produce some URL like `https://powerline.ne/#/post/314`, but what should the other consumers who will find it on facebook do with that link? 

It makes sense to share such URL in two cases:
- there is web portal which can resolve such link
- if the user has powerline.app installed in the phone where he clicked the URL, it is possible to open powerline app and go to the content of the link (but this url-recognition has to be configured first).

but currently none of the options is available.

**Comment by jterps08** [comment]
Your two cases are correct. The Facebook and other share buttons are supposed to share that not-yet-implemented URL routing that I have already designed so that other users are pointed to the Powerline app if on mobile device and have it (deeplinking) OR that they are pointed to our web app, which obviously doesn't exist yet. 

It might be easiest to simply put a dialog box in that says "This feature will be available in the next release." or something when tapped...

**Comment by petervojtek** [comment]
@jterps08 , and wouldn't it be better to remove the button temporarily?

**Comment by jterps08** [comment]
I was trying to convey that we have a feature planned for people that they'll probably want... Even if the message said "This feature is temporarily unavailable." would be better. It's been over a year since our last release. People don't expect to lose functionality, they expect to gain it...

Your choice. It's P3 to me. So your choice.

**Comment by petervojtek** [comment]
ok, I will add there the popup.

**Comment by austinpapp** [comment]
Yes. People will most likely want this. However showing a button that doesn't work with a pop-up of "temp unavailable" is insanely frustrating to people versus not having it at all. If it isn't working right, we should not have it present. Consider that a new feature on next release.

**Comment by jterps08** [comment]
It's also insanely frustrating for people to wait a year for a new release and to have less functionality in the next release than they had in the first one.
