### ISSUE TITLE
Unable to use Groups search - endless loop in JS

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#77]
Visit `http://localhost:8100/#/groups/search`

JS console is flooded with:

```
ionic.bundle.min.js:139 Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.3/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…%20b(e%2Cc%2Cd)%7D%22%2C%22newVal%22%3A1970%2C%22oldVal%22%3A1969%7D%5D%5D
    at Error (native)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:37:416
    at n.$digest (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:164:96)
    at n.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:166:269)
    at l (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:118:152)
    at F (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:122:187)
    at XMLHttpRequest.K.onload (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:123:220)(anonymous function) @ ionic.bundle.min.js:139(anonymous function) @ ionic.bundle.min.js:111$apply @ ionic.bundle.min.js:166l @ ionic.bundle.min.js:118F @ ionic.bundle.min.js:122K.onload @ ionic.bundle.min.js:123
ionic.bundle.min.js:37 Uncaught Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.3/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…%20b(e%2Cc%2Cd)%7D%22%2C%22newVal%22%3A1970%2C%22oldVal%22%3A1969%7D%5D%5D
```

and searching for "Bucklin" group throws error:

```
11ionic.bundle.min.js:139 TypeError: Cannot read property 'slice' of undefined
    at http://localhost:8100/js/services/groups.js:267:32
    at http://localhost:8100/lib/underscore/underscore-min.js:5:2011
    at Function.h.each.h.forEach (http://localhost:8100/lib/underscore/underscore-min.js:5:960)
    at Function.h.filter.h.select (http://localhost:8100/lib/underscore/underscore-min.js:5:1988)
    at h.(anonymous function) [as filter] (http://localhost:8100/lib/underscore/underscore-min.js:5:14825)
    at Object.search (http://localhost:8100/js/services/groups.js:256:35)
    at Object.$scope.$watch.$scope.searchItems (http://localhost:8100/js/controllers/groups.js:70:43)
    at n.$digest (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:163:124)
    at n.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:166:269)
    at l (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:118:152)
    at F (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:122:187)
    at XMLHttpRequest.K.onload (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:123:220)(anonymous function) @ ionic.bundle.min.js:139(anonymous function) @ ionic.bundle.min.js:111$digest @ ionic.bundle.min.js:163$apply @ ionic.bundle.min.js:166l @ ionic.bundle.min.js:118F @ ionic.bundle.min.js:122K.onload @ ionic.bundle.min.js:123
ionic.bundle.min.js:139 Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.3/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…%20b(e%2Cc%2Cd)%7D%22%2C%22newVal%22%3A5886%2C%22oldVal%22%3A5885%7D%5D%5D
    at Error (native)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:37:416
    at n.$digest (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:164:96)
    at n.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:166:269)
    at l (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:118:152)
    at F (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:122:187)
    at XMLHttpRequest.K.onload (http://localhost:8100/lib/ionic/js/ionic.bundle.min.js:123:220)(anonymous function) @ ionic.bundle.min.js:139(anonymous function) @ ionic.bundle.min.js:111$apply @ ionic.bundle.min.js:166l @ ionic.bundle.min.js:118F @ ionic.bundle.min.js:122K.onload @ ionic.bundle.min.js:123
```

**Comment by jterps08** [comment]
Note: the purpose of the groups/search function is to search for a group that the user may or may not be joined to. If I am not a member of any groups, I would use this function to search for "Save the Whales" in order to display that group in the results in the app and tap the join button.

A Note On Joining A Group:
There are a few different ways to join a group:
1) In the group profile, tap the Join button
2) View the group in the Group Search results, tap the + Join button next to the group.
3) Receive an invite to join the group (which would appear in your Announcements/Inbox (mail icon)) and click Join instead of Ignore
4) The system may be setup to automatically invite you to a group upon user registration according to server PR 46 in the server repo.
4b) Special auto-joining is setup to join a user to their town/state/country groups as well as the African Union and the European Union groups IF they live in an eligible country -- PR #72/73/74 on the server repo. 
5) The author of a post may invite all the users who upvoted his post to a specific group (partially available via PR # 47 in the server repo. 

Under any of the above scenarios (except 4b):
A) A user may be available to join freely and instantly with no other provided information or review.
B) A user may be required to enter a passcode to join the group successfully
C) A user may be required to wait for manual review by the group leader to accept them into the group. 
D) In addition to A/B/C, a user may be required to enter "Required Information" to join the group. This is essentially group-specific profile information. For example, in "Save the Whales" a Required field might ask "What is your favorite whale?". When the group leader reviews his membership roster, he will be able to see the user's response to this question next to the group member's other accessible information.

**Comment by petervojtek** [comment]
Adding user to group via Home screen -> Newsfeed -> More button -> Add group also fails the same way.
